- 000-template.md
- README.md
- add a template for future Strimzi proposals, based on existing
proposals
- was originally added under #6 
Signed-off-by: Matthew Chirgwin <chirmatt@uk.ibm.com>
> feat: propose proposal template

- 011-admin-server.md
- 012-admin-server.md
- README.md
for Strimzi.
Signed-off-by: Graeme McRobert <mcrobert@uk.ibm.com>
> Proposal for an admin REST and GraphQL Server

- 018-rest-admin-api.md
- README.md
When the REST API proposal was merged, it was not properly numbered and it was not added to the index in the README.md file. This PR tries to fix it. It also fixes typo in the proposal.
> Fix wrong numbering and missing index record for the REST API proposal

- 019-restruture-the-installation-files.md
- README.md
This proposal suggests changes to the way we use the examples and installation files in the `master` branch of the operators repository. It aims to make it more friendly to new users.
I was a bit undecided between keeping the existing directories for the release files or moving them to `deploy` subdirectory. If people prefer the rejected alternative I'm fine to change the proposal.
> Restructure the installation files

- 020-rename-default-branch-of-strimzi-github-repositories.md
- README.md
This proposal suggests to use `main` as the new name for the default branch in all our GitHub repositories.
> Rename the default branch of Strimzi GitHub repositories

- 026-service-account-patching.md
- README.md
Today, Strimzi has a special treatment for Service Accounts and their reconciliation. This proposal suggests to introduce the same handling for Service accounts as we have for other resources and explains the motivation for it.
> Add Service Account patching proposal

- 023-using-ubi8-as-base-image.md
- README.md
This proposal suggests to use UBI8 as the new base image for Strimzi projects.
> Using Red Hat Universal Base Image 8 as the new Strimzi base image

- README.md
Unfortunately, I used incorrect link for the proposal 23 when adding it to the index (it is without the `.md` extension), so the link does not work. This PR fixes it.
> Fix broken link in the proposal index

- README.md
This PR fixes the incorrect link for the Service Binding proposal which has wrong number in the filename.
> Fix link to the service Binding proposal

- 034-deprecate-and-remove-mirror-maker-2-extensions.md
- README.md
In Kafka 3.0.0, Mirror Maker 2 introduces its own `IdentityReplicationPolicy`. This policy provides the same features as Strimzi's own `IdentityReplicationPolicy`. It does not seem to make sense to maintain our own policy in parallel to Apache Kafka. So this proposal suggests the plan for deprecating and removing our own policy and the [_Mirror Maker 2 Extensions_ project](https://github.com/strimzi/mirror-maker-2-extensions).
> Deprecate and remove Mirror Maker 2 extensions

- 035-cruise-control-scaling-brokers.md
- 035-rebalance-types-scaling-brokers.md
- README.md
This proposal is about adding the Cruise Control support for running rebalancing when the Apache Kafka cluster is scaled up or down.
It leverages the usage of a couple of different Cruise Control endpoints to avoid a full rebalance across all the already existing brokers but just moving replicas to the newly added ones (after scaling up) or move replicas out from the removed ones (before scaling down) in order to have less data movement, CPU usage and so on.
It's doesn't provide automation but it's user driven by using an enhanced `KafkaRebalance` resource with new types of rebalancing.
> Extending the `KafkaRebalance` resource with rebalance types to help scaling the Apache Kafka cluster

- 036-kraft-mode.md
- README.md
This PR proposes to add initial support for ZooKeeper-less Kafka / KRaft mode. The initial proposal contains many limitations and it does not cover the API changes expected to be done before the production-ready KRaft support. But it should simplify the development of the KRaft mode in Strimzi and make it easier to test it.
This proposal expects the code to be mostly based on my [_Escape the Zoo_ prototype branch](https://github.com/strimzi/strimzi-kafka-operator/compare/main...scholzj:escape-the-zoo-2?expand=1).
> KRaft mode proposal

- 035-rebalance-types-scaling-brokers.md
While developing #52 (through this PR https://github.com/strimzi/strimzi-kafka-operator/pull/6800) we decided to change the mode names as: `full`, `add-brokers` and `remove-brokers`.
This trivial PR just reflects in the proposal what was decided to take everything consistent.
> Updated rebalancing mode names

- 037-pluggable-pod-security-profiles.md
- README.md
This proposals replaces #48. It suggests pluggable mechanism for PodSecurityProviders and implementation which matches the Kubernetes _restricted_ Pod Security Standards profile. This should make it easier for users to run under this profile.
In addition to the proposal, there is also a draft implementation which can be seen [here](https://github.com/strimzi/strimzi-kafka-operator/compare/main...scholzj:plugable-pod-security-profiles?expand=1). It currently doesn't have the docs, Javadoc and full test coverage, but it is fully functional under the restricted profile.
> Pluggable security configuration providers

- 043-deprecate-and-remove-jmxtrans.md
- README.md
This proposal suggests deprecation and removal of the JMX Trans tool which is part of the Kafka custom resource and does nto seem to be developed anymore. It proposes the timeline as well as the suggested steps for the different phases.
> Deprecate and remove JMX Trans

- 044-StrimziPodSets-graduation.md
- README.md
Thsi PR proposes an updated schedule for the graduation of `StrimziPodSet` support and moving the `UseStrimziPodSets` feature gate to GA. Please review the proposal for more details.
> Updated `StrimziPodSet` graduation schedule

- README.md
There is a typo in the link to proposal 047 - Cluster Wide Volume Usage Quota Management. This PR fixes the typo.
> Fix typo in link to proposal 47

- 045-Stable-identities-for-Kafka-Connect-worker-nodes.md
- 050-Kafka-Node-Pools.md
This PR updates the graduation releases for the Node Pool and Stable Connect identities feature gates:
* Node pools were merged only in 0.36 instead of the initially expected 0.35
* Moving StableConnectIdentities to beta was postponed because of the informer issues in the Kubernetes Client
> Update the Strimzi releases when the feature gates are expected to graduate

- 057-marking-zk-kraft-clusters.md
- 057-run-zk-kraft-clusters-parallel.md
- README.md
This PR adds a proposal to allow running ZooKeeper and KRaft based clusters in parallel when the KRaft feature gate is enabled.
> Allow running ZooKeeper and KRaft based clusters in parallel

- README.md
Adding the missing latest merged proposal "Deprecate and remove EnvVarConfigProvider" to the README.
> Updated README with latest "Deprecate and remove EnvVarConfigProvider" proposal

- 066-topic-replication-factor-change.md
- README.md
Proposal to enable the topic replication factor change directly from KafkaTopic resource when Cruise Control integration is enabled
There is also a [draft implementation](https://github.com/strimzi/strimzi-kafka-operator/pull/9483).
> Add topic replication factor change

- 071-deprecate-bridge-openapi-2.md
- README.md
This proposal is about deprecating and removing the OpenAPI v2 support across the next two Strimzi HTTP bridge releases.
> Added proposal about OpenAPI v2 deprecation and removal on the Strimzi HTTP bridge

- 073-improve-handling-of-CA-renewals-and-replacements-in-client-based-operands.md
- README.md
This proposal improves the API for configuring the trusted certificates in Strimzi Operands and should help to address strimzi/strimzi-kafka-operator#7726.
One of the things I was least sure about is the last _rejected alternative_: `Making certificate and extension fields completely optional`. So if anyone has any strong opinions about it, please let me know 😉.
> Improve handling of CA renewals and replacements in operands based on the Kafka clients

- 081-unregistration-of-KRaft-nodes.md
- README.md
This proposal describes how we could handle the node unregistration which is part of the existing KRaft limitations.
> Unregistration of KRaft nodes

- 084-templating-host-and-advertisedHost-fields.md
- README.md
This proposal suggests a way how to (optionally) template the `host` and `advertisedHost` fields in the listener configurations in the Kafka CR. Thanks to that, Strimzi users should not need to specify these for every single broker if they are using some predictable pattern.
> Add possibility to provide a template to generate `host` and `advertisedHost` fields

- 088-support-mounting-of-CSI-volumes.md
- README.md
This proposal adds support for mounting CSI volumes in the additional volumes template. This can be used to mount various secrets using special CSI drivers. Implementation of this proposal should help to address https://github.com/strimzi/strimzi-kafka-operator/issues/5277.
> Add support for mounting CSI volumes

- 108-list-unregister-nodes-admin-api.md
After some feedback on the corresponding implementation PR https://github.com/strimzi/strimzi-kafka-operator/pull/11729 to simplify the implementation, this PR updates the proposal to reflect such changes.
It's not something we usually do but I would like to avoid having a so stale proposal compared to the implementation.
> Updated the unregister nodes API proposal due to implementation changes

- 112-Strimzi-v1-CRD-API-and-1.0.0-release.md
- 113-Strimzi-v1-CRD-API-and-1.0.0-release.md
- README.md
This PR opens the proposal for how we should deal with the `v1` CRD API, its introduction, removal of the older API versions, and finally the release of Strimzi 1.0.0. While there are some open points left, they can be done in a separate follow-up proposals. So please do not hesitate to review it 😉.
> Strimzi `v1` CRD API and 1.0.0 release

- 117-v1-CRD-API-Conversion-Tool.md
- README.md
This proposal covers the Conversion Tool for converting the `v1beta2` API to the `v1` API. The tool will be needed by all Strimzi users before upgrading to Strimzi 0.52 / 1.0.0 version, which removes support for the `v1beta2` and older APIs. The tool is mostly based on the `v1beta2` conversion tool we used back then. And its UX and the required upgrade workflow correspond to it as well.
> `v1` CRD API Conversion Tool

- 112-running-multiple-versions-of-connector-plugins.md
- 118-running-multiple-versions-of-connector-plugins.md
- README.md
Add `version` field to `KafkaConnector` CR for users to specify the version of the connector they want to run.
Relates to https://github.com/strimzi/strimzi-kafka-operator/issues/11009
> Running multiple versions of connector plugins
